### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by icemac** [zopefoundation/five.globalrequest#5]
#4 deprecated the whole package as it is now integrated in Zope 4.0a3.

A release is needed.
My PyPI name is `icemac`.

**Comment by icemac** [comment]
Released to PyPI: https://pypi.org/project/five.globalrequest/99.0/

**Comment by LadyNamedLaura** [comment]
@icemac please test if your package can be installed before uploading it in the future (see #6 )

**Comment by hannosch** [comment]
I've cut a new 99.1 release with the fix.

**Comment by icemac** [comment]
@SimonPe Sorry for the inconvenience this error has caused.
You are hereby invited to review my pull requests to prevent such errors in the future.
